### ISSUE TITLE
[Feature Request] Add Support for PMDG 777 (when it is released)

### ISSUE THREAD

**Issue by berndverst** [Fergo/fcdu-bugtracker#19]
This is just a roadmap tracking issue for the feature request to add support for the PMDG 777 planes (e.g. 777-300er, 777-200lr) when they will start releasing in the next 2 months. My understanding is that the PMDG SDK / API should be the same for those, so your app might already work. However, it would be great to have your official response on supporting the 777 in this app.

Thanks!

P.S.: I just bought your app a moment ago :)

**Comment by Fergo** [comment]
Hi! Thanks for purchasing Fergo Virtual CDU.

Yes, 777 support is planned and I already got in touch with PMDG for the SDK, but it's not available yet.

KR,
Fergo

**Comment by berndverst** [comment]
Awesome. Thanks Fergo!
