### ISSUE TITLE
MSG - OFST - CALL - FAIL indicators

### ISSUE THREAD

**Issue by ProfKenWord** [Fergo/fcdu-bugtracker#6]
When I press the lamp test in the PMDG 737, MSG, OFST, **CALL** and FAIL lights up on the FMC in the cockpit.

You have MSG, OFST, **DSPY**, FAIL on. In addition, DSPY and FAIL "hang together" in your cdu.html and light up together, that shouldn't be the case.

So:
+ Replace DSPY with CALL
+ Disconnect connection with FAIL
+ FAIL lits amber, CALL should lit white

**Comment by Fergo** [comment]
Good points. 
Should be some pretty straightforward fixes. I'll try to release an updated version this weekend.

**Comment by Fergo** [comment]
New version pushed to flightsim.to. It should be available in the next few hours.

✔ Replace DSPY with CALL
✔ Disconnect connection with FAIL
✔  FAIL lits amber, CALL should lit white

Closing this issue.

**Comment by Fergo** [comment]
Changes implemented
